# Copyright (c) 2017-present, Facebook, Inc. All rights reserved.
#
# You are hereby granted a non-exclusive, worldwide, royalty-free license to use,
# copy, modify, and distribute this software in source code or binary form for use
# in connection with the web services and APIs provided by Facebook.
#
# As with any software that integrates with the Facebook platform, your use of
# this software is subject to the Facebook Platform Policy
# [http://developers.facebook.com/policy/]. This copyright notice shall be
# included in all copies or substantial portions of the software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# FB:AUTOGEN

module FacebookAds
  # This class is auto-generated.

  # For any issues or feature requests related to this class, please let us know
  # on github and we'll fix in our codegen framework. We'll not be able to accept
  # pull request for this class.

  class DeliveryWindow < AdObject

    field :ad, 'int'
    field :ae, 'int'
    field :af, 'int'
    field :ag, 'int'
    field :ai, 'int'
    field :al, 'int'
    field :all, 'int'
    field :am, 'int'
    field :an, 'int'
    field :ao, 'int'
    field :aq, 'int'
    field :ar, 'int'
    field :as, 'int'
    field :at, 'int'
    field :au, 'int'
    field :aw, 'int'
    field :ax, 'int'
    field :az, 'int'
    field :ba, 'int'
    field :bb, 'int'
    field :bd, 'int'
    field :be, 'int'
    field :bf, 'int'
    field :bg, 'int'
    field :bh, 'int'
    field :bi, 'int'
    field :bj, 'int'
    field :bl, 'int'
    field :bm, 'int'
    field :bn, 'int'
    field :bo, 'int'
    field :bq, 'int'
    field :br, 'int'
    field :bs, 'int'
    field :bt, 'int'
    field :bv, 'int'
    field :bw, 'int'
    field :by, 'int'
    field :bz, 'int'
    field :ca, 'int'
    field :cc, 'int'
    field :cd, 'int'
    field :cf, 'int'
    field :cg, 'int'
    field :ch, 'int'
    field :ci, 'int'
    field :ck, 'int'
    field :cl, 'int'
    field :cm, 'int'
    field :cn, 'int'
    field :co, 'int'
    field :cr, 'int'
    field :cu, 'int'
    field :cv, 'int'
    field :cw, 'int'
    field :cx, 'int'
    field :cy, 'int'
    field :cz, 'int'
    field :de, 'int'
    field :dj, 'int'
    field :dk, 'int'
    field :dm, 'int'
    field :_do, 'int'
    field :dz, 'int'
    field :ec, 'int'
    field :ee, 'int'
    field :eg, 'int'
    field :eh, 'int'
    field :er, 'int'
    field :es, 'int'
    field :et, 'int'
    field :fi, 'int'
    field :fj, 'int'
    field :fk, 'int'
    field :fm, 'int'
    field :fo, 'int'
    field :fr, 'int'
    field :ga, 'int'
    field :gb, 'int'
    field :gd, 'int'
    field :ge, 'int'
    field :gf, 'int'
    field :gg, 'int'
    field :gh, 'int'
    field :gi, 'int'
    field :gl, 'int'
    field :gm, 'int'
    field :gn, 'int'
    field :gp, 'int'
    field :gq, 'int'
    field :gr, 'int'
    field :gs, 'int'
    field :gt, 'int'
    field :gu, 'int'
    field :gw, 'int'
    field :gy, 'int'
    field :hk, 'int'
    field :hm, 'int'
    field :hn, 'int'
    field :hr, 'int'
    field :ht, 'int'
    field :hu, 'int'
    field :id, 'int'
    field :ie, 'int'
    field :il, 'int'
    field :im, 'int'
    field :in, 'int'
    field :io, 'int'
    field :iq, 'int'
    field :ir, 'int'
    field :is, 'int'
    field :it, 'int'
    field :je, 'int'
    field :jm, 'int'
    field :jo, 'int'
    field :jp, 'int'
    field :ke, 'int'
    field :kg, 'int'
    field :kh, 'int'
    field :ki, 'int'
    field :km, 'int'
    field :kn, 'int'
    field :kp, 'int'
    field :kr, 'int'
    field :kw, 'int'
    field :ky, 'int'
    field :kz, 'int'
    field :la, 'int'
    field :lb, 'int'
    field :lc, 'int'
    field :li, 'int'
    field :lk, 'int'
    field :lr, 'int'
    field :ls, 'int'
    field :lt, 'int'
    field :lu, 'int'
    field :lv, 'int'
    field :ly, 'int'
    field :ma, 'int'
    field :mc, 'int'
    field :md, 'int'
    field :me, 'int'
    field :mf, 'int'
    field :mg, 'int'
    field :mh, 'int'
    field :mk, 'int'
    field :ml, 'int'
    field :mm, 'int'
    field :mn, 'int'
    field :mo, 'int'
    field :mp, 'int'
    field :mq, 'int'
    field :mr, 'int'
    field :ms, 'int'
    field :mt, 'int'
    field :mu, 'int'
    field :mv, 'int'
    field :mw, 'int'
    field :mx, 'int'
    field :my, 'int'
    field :mz, 'int'
    field :na, 'int'
    field :nc, 'int'
    field :ne, 'int'
    field :nf, 'int'
    field :ng, 'int'
    field :ni, 'int'
    field :nl, 'int'
    field :no, 'int'
    field :np, 'int'
    field :nr, 'int'
    field :nu, 'int'
    field :nz, 'int'
    field :om, 'int'
    field :pa, 'int'
    field :pe, 'int'
    field :pf, 'int'
    field :pg, 'int'
    field :ph, 'int'
    field :pk, 'int'
    field :pl, 'int'
    field :pm, 'int'
    field :pn, 'int'
    field :pr, 'int'
    field :ps, 'int'
    field :pt, 'int'
    field :pw, 'int'
    field :py, 'int'
    field :qa, 'int'
    field :re, 'int'
    field :ro, 'int'
    field :rs, 'int'
    field :ru, 'int'
    field :rw, 'int'
    field :sa, 'int'
    field :sb, 'int'
    field :sc, 'int'
    field :sd, 'int'
    field :se, 'int'
    field :sg, 'int'
    field :sh, 'int'
    field :si, 'int'
    field :sj, 'int'
    field :sk, 'int'
    field :sl, 'int'
    field :sm, 'int'
    field :sn, 'int'
    field :so, 'int'
    field :sr, 'int'
    field :ss, 'int'
    field :st, 'int'
    field :sv, 'int'
    field :sx, 'int'
    field :sy, 'int'
    field :sz, 'int'
    field :tc, 'int'
    field :td, 'int'
    field :tf, 'int'
    field :tg, 'int'
    field :th, 'int'
    field :tj, 'int'
    field :tk, 'int'
    field :tl, 'int'
    field :tm, 'int'
    field :tn, 'int'
    field :to, 'int'
    field :tr, 'int'
    field :tt, 'int'
    field :tv, 'int'
    field :tw, 'int'
    field :tz, 'int'
    field :ua, 'int'
    field :ug, 'int'
    field :um, 'int'
    field :us, 'int'
    field :uy, 'int'
    field :uz, 'int'
    field :va, 'int'
    field :vc, 'int'
    field :ve, 'int'
    field :vg, 'int'
    field :vi, 'int'
    field :vn, 'int'
    field :vu, 'int'
    field :wf, 'int'
    field :ws, 'int'
    field :xk, 'int'
    field :ye, 'int'
    field :yt, 'int'
    field :za, 'int'
    field :zm, 'int'
    field :zw, 'int'
    has_no_get
    has_no_post
    has_no_delete

  end
end
